config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/calculadora/:n1/:n2',     to: 'calculator#home'
  get '/calculadora/:n1/:n2/:op', to: 'calculator#result', as: 'calc_res'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculator_controller.rb
class CalculatorController < ActionController::Base
    def home
        @n1 = params[:n1].to_i
        @n2 = params[:n2].to_i
    end

    def result
        n1 = params[:n1].to_f
        n2 = params[:n2].to_f

        case params[:op]
        when "sum"
            @result = n1 + n2
        when "sub"
            @result = n1 - n2
        when "mul"
            @result = n1 * n2
        when "div"
            @result = n1 / n2
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calculator/home.html.erb
<%= link_to  "Somar", calc_res_path(op: 'sum') %>
<%= link_to  "Subtrair", calc_res_path(op: 'sub') %>
<%= link_to  "Multiplicar", calc_res_path(op: 'mul') %>
<%= link_to  "Dividir", calc_res_path(op: 'div') %>

app/views/calculator/result.html.erb
<h1><%=@result%></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aula1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>